### ISSUE TITLE
Game doesn't detect when I join a lobby

### ISSUE THREAD

**Issue by sALTaccount** [ottomated/CrewLink#28]
For whatever reason, CrewLink doesn't detect when I join or create a lobby. The CrewLink screen stays on "menu" the entire time, no matter what I do. I've tried reinstalling among us, reinstalling CrewLink and restarting my computer. Nothing I do can get CrewLink to work. If you need any other information for debugging you can add me on discord: 0x1529#4871

**Comment by Sttiuny** [comment]
Same issue

**Comment by DrPastilletes** [comment]
same

**Comment by MatadorProBr** [comment]
This probably happened because Among Us updated.

**Comment by rohitsandhu** [comment]
same

**Comment by Nemoic** [comment]
same

**Comment by neil-lobo** [comment]
> This probably happened because Among Us updated.

My friends and I have been playing on the latest version of the game for the past week, and it's been fine. It is also important to note that you shouldn't be playing on the beta version of the game. This is not mentioned in the repo's readme but it is in the installation video.

**Comment by sALTaccount** [comment]
I don't think I'm playing on the beta version, I'm just playing the latest version of among us I believe. Is there any way to check if you are on the beta version? It works just fine for my friend

**Comment by neil-lobo** [comment]
if you're on the beta it should say "[beta]" at the end of the name of the game in your game library

![image](https://user-images.githubusercontent.com/36115155/100486316-5c505a00-30d1-11eb-8c53-f15578619a89.png)

If you're not on the beta it may be some other issue, but I doubt it's because of a game update since it would probably break for everyone if that were the case.

**Comment by Chipxzx** [comment]
the same thing is happening to me

**Comment by sALTaccount** [comment]
yeah I'm not playing on the beta, what's weird is it works just fine for my friend so it's not anything to do with an among us update

**Comment by blu2ru** [comment]
If you open crewlink as admin and follow these steps, the problem should be resolved:

press `CTRL-SHIFT-I,` press the `>>` at the top, select `Console,` paste `(new (require('electron-store'))()).set('offsets', {})` and press enter, then restart crewlink

**Comment by sALTaccount** [comment]
that worked, thank you!

**Comment by raqueru** [comment]
> If you open crewlink as admin and follow these steps, the problem should be resolved:
> 
> press `CTRL-SHIFT-I,` press the `>>` at the top, select `Console,` paste `(new (require('electron-store'))()).set('offsets', {})` and press enter, then restart crewlink

My friend tried this and it gave the message "undefined" and didn't work.... What was supposed to say?

**Comment by heygleeson** [comment]
I'm also getting an 'undefined' message when adding that to the console, still having the same issue as the topic. Playing Among Us **v2020.11.17s**.

**Comment by nofriends69** [comment]
i still get undefined even after deleting the crew link folder

**Comment by raqueru** [comment]
> i still get undefined even after deleting the crew link folder

we end up using version 1.1.1 and it worked fine
I guess its a way out while they dont fix this bug

**Comment by nofriends69** [comment]
version 1.1.1 didnt work either

**Comment by neil-lobo** [comment]
> i still get undefined even after deleting the crew link folder

undefined is the expected output

**Comment by raqueru** [comment]
> version 1.1.1 didnt work either

that's weird, for me and my friends it worked just fine, maybe the firewall is blocking it?

**Comment by nofriends69** [comment]
are you on the latest version of among us

**Comment by raqueru** [comment]
> are you on the latest version of among us

yep

**Comment by khaya93** [comment]
Set your game language to english, and it should work fine. I was playing in spanish with some friend and we were having this issue we switched to english and it started working perfectly.

**Comment by nofriends69** [comment]
im getting an error saying that it cant get offsets from this link. the end of the link has 2020.10.8. i think its supposed to be 2020.11.17 and it will fix my problem but i dont know how to change it

**Comment by Ryanneetrte** [comment]
Does anyone have another solution?

**Comment by neil-lobo** [comment]
> im getting an error saying that it cant get offsets from this link. the end of the link has 2020.10.8. i think its supposed to be 2020.11.17 and it will fix my problem but i dont know how to change it

%appdata%/crewlink/config.json

**Comment by MatadorProBr** [comment]
> > im getting an error saying that it cant get offsets from this link. the end of the link has 2020.10.8. i think its supposed to be 2020.11.17 and it will fix my problem but i dont know how to change it
> 
> %appdata%/crewlink/config.json

i deleted the file and opened the crewnode again, and likewise, it does not detect bruh

**Comment by neil-lobo** [comment]
> > > im getting an error saying that it cant get offsets from this link. the end of the link has 2020.10.8. i think its supposed to be 2020.11.17 and it will fix my problem but i dont know how to change it
> > 
> > 
> > %appdata%/crewlink/config.json
> 
> i deleted the file and opened the crewnode again, and likewise, it does not detect bruh

I don't think you should be deleting it, I was only replying to the person that asked where to find the offset version.

**Comment by PapaWorst** [comment]
anyone get a fix for this?  Im having the same issue today?

**Comment by neil-lobo** [comment]
> anyone get a fix for this? Im having the same issue today?

The voice server that you're connecting to needs to update its offset file since there was just an update for the game, although, there are still some issues with the updated offsets. It will probably take a little time for them to be completely updated

**Comment by kewin100** [comment]
Still to this day doesnt work

**Comment by reipowertools** [comment]
I downloaded the CrewLink today and Among Us got an update yesterday. I'm having this issue with detection. Should I try to use an older version of AmongUs or wait for a CrewLink update?

**Comment by WittyGang** [comment]
Yea I have this problem too i downloaded it today i setup everythig and it just says Menu all the time

**Comment by MatadorProBr** [comment]
> Yea I have this problem too i downloaded it today i setup everythig and it just says Menu all the time

This is caused because of the new update of Among Us that ended up breaking the CrewLink and have to wait for Ottomated to solve this problem but have a solution for this, look the issue in [#623](https://github.com/ottomated/CrewLink/issues/623#issuecomment-793888862) that solves this problem.

**Comment by FNAFman201** [comment]
> If you open crewlink as admin and follow these steps, the problem should be resolved:
> 
> press `CTRL-SHIFT-I,` press the `>>` at the top, select `Console,` paste `(new (require('electron-store'))()).set('offsets', {})` and press enter, then restart crewlink

its not working for me

**Comment by MatadorProBr** [comment]
> its not working for me
@FNAFman201 please read my [last message](https://github.com/ottomated/CrewLink/issues/28#issuecomment-808818604) (not this message but the other)

**Comment by Floofyyy** [comment]
Hey, I'm having the same issue. When I launch crew link it doesn't detect my lobby. Has anyone solved this issue yet?
