### ISSUE TITLE
[FEATURE] 32 bit version 

### ISSUE THREAD

**Issue by Yesitzme** [ottomated/CrewLink#436]
Hello everyone 
I love what you did with this software & making the game more fun and all my friends tried it and it works perfectly with the 64 bit windows. 
Can you please give us a date when the 32 bit version will come out? Or a way to install it? 
Thank so much

**Comment by OhMyGuus** [comment]
This is an duplicate of #426 but I recommend u to use a fork of Crewlink until the pull request #263 is merged. 
Like mine: https://github.com/OhMyGuus/BetterCrewLink/releases 
or other forks with that branched merged that u can find on: 
https://github.com/ottomated/CrewLink/network/members

**Comment by Yesitzme** [comment]
> This is an duplicate of #426 but I recommend u to use a fork of Crewlink until the pull request #263 is merged.
> Like mine: https://github.com/OhMyGuus/BetterCrewLink/releases
> or other forks with that branched merged that u can find on:
> https://github.com/ottomated/CrewLink/network/members

Thank you,
But I tried urs but now the problem shown is "A javascript error occured in the main process "

**Comment by SADMaster04** [comment]
> > This is an duplicate of #426 but I recommend u to use a fork of Crewlink until the pull request #263 is merged.
> > Like mine: https://github.com/OhMyGuus/BetterCrewLink/releases
> > or other forks with that branched merged that u can find on:
> > https://github.com/ottomated/CrewLink/network/members
> 
> Thank you,
> But I tried urs but now the problem shown is "A javascript error occured in the main process "

SAMEE

**Comment by SADMaster04** [comment]
i dont understand the other option

**Comment by OhMyGuus** [comment]
Sorry if you guys didn't find another fork yet, its fixed in the .3 version of my fork.

**Comment by Yesitzme** [comment]
> Oops sorry! if you guys didn't find another fork yet, its fixed in the .3 version of my fork.

Thank you for your help, but now this is shown up "could not find your steam install path "
![Sans titre](https://user-images.githubusercontent.com/76435834/102920524-324d4600-448b-11eb-8420-551cfb0347a6.png)

**Comment by OhMyGuus** [comment]
> > Oops sorry! if you guys didn't find another fork yet, its fixed in the .3 version of my fork.
> 
> Thank you for your help, but now this shown up "could not find your steam install path "
> ![Sans titre](https://user-images.githubusercontent.com/76435834/102920524-324d4600-448b-11eb-8420-551cfb0347a6.png)

The open game button doesn't work yet, just start the game with steam and it should detect it. If it doesn't detect it then you might need to run it as admin.

**Comment by Yesitzme** [comment]
> > > Oops sorry! if you guys didn't find another fork yet, its fixed in the .3 version of my fork.
> > 
> > 
> > Thank you for your help, but now this shown up "could not find your steam install path "
> > ![Sans titre](https://user-images.githubusercontent.com/76435834/102920524-324d4600-448b-11eb-8420-551cfb0347a6.png)
> 
> The open game button doesn't work yet, just start the game with steam and it should detect it. If it doesn't detect it then you might need to run it as admin.

I started the game with steam and I opened crewlink as admin, but still the same 😔
I will to someone here with 32 bit to right it, to see if the problem is only in my computer or not

**Comment by OhMyGuus** [comment]
Will fix it sorry my fault.. 

> > > > Oops sorry! if you guys didn't find another fork yet, its fixed in the .3 version of my fork.
> > > 
> > > 
> > > Thank you for your help, but now this shown up "could not find your steam install path "
> > > ![Sans titre](https://user-images.githubusercontent.com/76435834/102920524-324d4600-448b-11eb-8420-551cfb0347a6.png)
> > 
> > 
> > The open game button doesn't work yet, just start the game with steam and it should detect it. If it doesn't detect it then you might need to run it as admin.
> 
> I started the game with steam and I opened crewlink as admin, but still the same 😔
> I will wait until someone here with 32 bit to try it, to see if the problem is only in my computer or not

Weird.. if it still doesn't work you can message me on Discord. ThaGuus#2140  then we can look at it easier.

**Comment by SADMaster04** [comment]
is it fixed yet?

**Comment by OhMyGuus** [comment]
> is it fixed yet?
If you download the Crewlink from my fork, it should work without problems. If it doesn't detect the game then it helps sometimes to run it as admin. 
https://github.com/OhMyGuus/BetterCrewLink/releases

**Comment by SADMaster04** [comment]
> > is it fixed yet?
> > If you download the Crewlink from my fork, it should work without problems. If it doesn't detect the game then it helps sometimes to run it as admin.
> > https://github.com/OhMyGuus/BetterCrewLink/releases

so its working on windows 7 32bit now?

**Comment by Yesitzme** [comment]
> > > is it fixed yet?
> > > If you download the Crewlink from my fork, it should work without problems. If it doesn't detect the game then it helps sometimes to run it as admin.
> > > https://github.com/OhMyGuus/BetterCrewLink/releases
> 
> so its working on windows 7 32bit now?

I don't know, I'm still waiting for it

**Comment by SADMaster04** [comment]
> > > > is it fixed yet?
> > > > If you download the Crewlink from my fork, it should work without problems. If it doesn't detect the game then it helps sometimes to run it as admin.
> > > > https://github.com/OhMyGuus/BetterCrewLink/releases
> > 
> > 
> > so its working on windows 7 32bit now?
> 
> I don't know, I'm still waiting for it

i tried it, and it downloaded, but we couldnt hear or speak to the windows 7 32bit device.
